### ISSUE TITLE
ERROR: No matching distribution found for inventree-ipn-generator

### ISSUE THREAD

**Issue by masteradit** [LavissaWoW/inventree-ipn-generator#7] opened 2024-06-07 17:31 UTC
I tried installing the plugin using the Inventree web interface and got this error:
![image](https://github.com/LavissaWoW/inventree-ipn-generator/assets/39951503/814e1a4f-136b-4ebf-aeff-7a9a72bad433)

I have enabled all the plugin settings:
![image](https://github.com/LavissaWoW/inventree-ipn-generator/assets/39951503/17a86f38-eb3c-45a7-ae1c-5d311d89923d)

Am I missing something?

Thanks in advance!

**Comment by LavissaWoW** [comment] 2024-06-08 16:24
Hi there! Could you check what Python version your InvenTree is running? I believe it's visible in the about tab.

I've tested the plugin for Python 3.10 and up, as that's what InvenTree 0.14 and up uses.

**Comment by LavissaWoW** [comment] 2024-08-16 22:39
@masteradit Did you resolve the problem?

**Comment by gid204** [comment] 2024-10-01 05:16
Hi @LavissaWoW 

I'm having the same issue:
<img width="1241" alt="image" src="https://github.com/user-attachments/assets/db7358cf-878a-4694-abfa-3fd5bab68e04">

Here is my About Inventree page:
<img width="1239" alt="image" src="https://github.com/user-attachments/assets/73958f0d-e76a-46d5-bdd9-9572b8537c54">

System info:
Ubuntu 20.04 installed using the [Installer Script](https://docs.inventree.org/en/stable/start/installer/#installer)

I think it pretty clear what the issue is, I just don't know what the best way to resolving it would be without breaking other dependencies.

Is there a clean way to update python?

Thanks!

**Comment by LavissaWoW** [comment] 2024-10-02 21:23
My own environment uses 3.10, and it's what InvenTree itself installed on my end.
But there's not really any reason that the plugin can't work on 3.9. Especially as Ubuntu 20.04 LTS uses that.

I'll update the code and make a new release that supports 3.9.x

**Comment by gid204** [comment] 2024-10-08 06:42
@LavissaWoW sorry to bother you, just wondering if you have a timeframe for when you will have time to get to this?
Thanks!

**Comment by LavissaWoW** [comment] 2024-10-08 15:25
Version requirements change in #9 
Release v0.1.2 is out on PyPi, and should be downloadable now.
Closing this in a couple of days if no one reports any problems

**Comment by gid204** [comment] 2024-10-09 01:27
Confirming installation is now successful for me using the Inventree web GUI.

Thanks!

**Comment by LavissaWoW** [comment] 2024-11-02 23:05
Installation working for Python 3.9 with v0.1.2

**Closed as completed by LavissaWoW** 2024-11-02 23:05 UTC
